### ISSUE TITLE
建议：打tag

### ISSUE THREAD

**Issue by shaunthegeek** [xiangminwang/oauth2-weibo#1]
需要打个tag，否则packagist composer里没有版本号，很危险。

https://packagist.org/packages/xiangminwang/oauth2-weibo

建议使用 语义化版本号： http://semver.org/lang/zh-CN/

比如 0.1.0

**Comment by xiangminwang** [comment]
@sinkcup  thanks for the nice hint, please checkout if the tag has been applied by now?

**Comment by shaunthegeek** [comment]
OK
